sitepoint/discourse-theme

assets/javascripts/discourse/templates/header.js.handlebars
=> Combine books and courses link on the main nav.

assets/javascripts/discourse/templates/header.js.handlebars
=> Update to previous update due to typo in the URL.

plugin.rb
- Also ensured we delete old site_customizations
[Trello card](https://trello.com/c/Zp6YdwWE/1058-add-fly-in-to-forums-change-hello-bar-code)
=> Updated hello-bar and fly-in for forums

assets/javascripts/discourse/templates/header.hbs
=> Add versioning to header

assets/javascripts/discourse/initializers/random-hello-bar.js.es6, assets/stylesheets/random-hello-bar.scss, plugin.rb
- hello bar content served from SP Forums Random Hello Bar plugin on sitepoint.com
=> Replace bsa fancybar with Random Hello Bar

plugin.rb
Trello: https://trello.com/c/jBwXSvU2/38-add-verified-alexa-to-sitepoint-sitepoint-premium-and-maybe-forums
Code snippet to be added through admin.
=> Add Alexa Claim & Certify customisation

assets/javascripts/discourse/initializers/random-hello-bar.js.es6, assets/stylesheets/random-hello-bar.scss, plugin.rb
- replaces bsa fancy bar with hello bar again
=> Restore hello bar

assets/javascripts/discourse/initializers/random-hello-bar.js.es6, plugin.rb
- also clear old settings from head_tag
=> Correct wp-admin ajax url

assets/stylesheets/common/base/topic-list.scss
Widens the category badges on the categories page
=> Widen the category badge on the categories page

assets/stylesheets/common/base/topic-list.scss, assets/stylesheets/mobile/topic-list.scss, plugin.rb
Moved the category badge styling for all other discourse pages to the theme
Added some Tag styling too
Removed tags from the mobile topic/latest view, as it was too cramped.
=> Category and Tag styling

assets/stylesheets/common/base/topic-list.scss
Fix the category display for Mobile on the /categories page
=> Category Button Styling for Mobile

assets/stylesheets/mobile/header.scss, plugin.rb
=> Remove the Header Links for Mobile

assets/javascripts/discourse/templates/header.hbs, assets/stylesheets/common/base/header.scss, assets/stylesheets/common/foundation/variables.scss, assets/stylesheets/desktop/header.scss, assets/stylesheets/mobile/header.scss, plugin.rb
Update the forum nav to match blog and Premium.
Hover states
Dropdown active state
Mobile
=> Update header nav styles

assets/stylesheets/common/base/header.scss
Trello: https://trello.com/c/hu9LFnvK/137-standardise-logomark-across-properties
Before
After
=> Reposition pm notifications and topic title

assets/javascripts/discourse/templates/header.hbs, plugin.rb
Trello: https://trello.com/c/sBmvlQEK/235-update-main-sitepoint-nav-across-sitepoint-premium-and-forums
=> Add Shop, remove Deals

assets/javascripts/discourse/components/maestro-modal-once.js.es6, assets/javascripts/discourse/components/maestro-outlet.js.es6, assets/javascripts/discourse/templates/components/maestro-modal-once.hbs, assets/javascripts/discourse/templates/connectors/below-footer/maestro.hbs, assets/javascripts/lib/local_storage.js.es6, assets/stylesheets/common/components/Button.scss, plugin.rb
Trello: https://trello.com/c/v5a9flnn/524-modal-on-sitepoint-forums
follows on from https://github.com/sitepoint/blog/pull/851 and https://github.com/sitepoint/sp-maestro/pull/51
Ember has a concept of outlets where components can be inserted via connectors eg. `assets/javascripts/discourse/templates/connectors/below-footer/maestro.hbs` will cause a `maestro-outlet` component to be inserted into the `plugin-below-footer` outlet.
`{{maestro-outlet templateAlias="Forums Below Footer"}}`
The `maestro-outlet` component will fetch a template from maestro for the given `templateAlias`/`widget name` and then render it. As it is rendered by Ember rather than just inserting into the dom the template can contain other Ember components (eg maestro-modal-once).
The `maestro-modal-once` component …
=> Add maestro-outlet and maestro-modal-once components plus Button styles

plugin.rb
The compiler is not included client side in production builds by default :(
=> Add client side template compiler

assets/javascripts/discourse/templates/components/topic-list.hbs, assets/javascripts/discourse/templates/connectors/topic-above-suggested/maestro.hbs, assets/stylesheets/common/base/bsa.scss, plugin.rb
Prevents page jump when BSA ad is inserted after page load
=> Add min height wrapper to bsa outlets

assets/javascripts/discourse/templates/connectors/above-user-preferences/sso_notice.hbs
=> Add sso notice

plugin.rb
Trello: https://trello.com/c/oJMpY6YM/87-investigate-demandbase-integration
=> Add DemandBase tag

assets/javascripts/discourse/templates/header.hbs, assets/javascripts/discourse/widgets/header.js.es6, plugin.rb
Trello: https://trello.com/c/VSSW1EbF/749-themes-link-in-forum-menu-bar
=> Add Themes link in top nav, update UTMs

assets/javascripts/discourse/components/maestro-outlet.js.es6, assets/javascripts/discourse/components/maestro-sub.js.es6, assets/javascripts/discourse/helpers/fifth-or-last.js.es6, assets/javascripts/discourse/initializers/discourse-theme.js.es6, assets/javascripts/discourse/templates/components/category-title-link.hbs, assets/javascripts/discourse/templates/components/maestro-outlet.hbs, assets/javascripts/discourse/templates/components/navigation-bar.hbs, assets/javascripts/discourse/templates/connectors/extra-nav-item/faq.hbs, assets/javascripts/discourse/widgets/header.js.es6, assets/javascripts/discourse/widgets/sitepoint-logo.js.es6, plugin.rb
=> 1.7.0.beta11

plugin.rb
The `SiteCustomization` model doesn't exist anymore and has been rolled into themes.
=> Refactor SiteCustomization to be a Theme

assets/javascripts/discourse/initializers/discourse-theme.js.es6, assets/javascripts/lib/live_ramp.js.es6
Trello: https://trello.com/c/u1O211le/1001-check-and-update-circulate
Adds the same LiveRamp script that exists on blog and premium to send hashed emails daily.
=> Add live ramp script

assets/javascripts/discourse/helpers/first-item.js.es6, assets/javascripts/discourse/templates/components/topic-list.hbs, plugin.rb
[Trello](https://trello.com/c/OXmTZzvq)
This will remove the BSA ads in community and replaced with proper.io
Also removed demandbase as requested by @mrlagmer
=> Replace BSA with proper.io

assets/javascripts/admin/templates/connectors/after-user-details/custom_fields.hbs, assets/javascripts/discourse/templates/connectors/after-nav-pills/new-message.js.es6, assets/stylesheets/common/base/header.scss, config/locales/client.en.yml, plugin.rb
Fixes the custom fields on the Admin > User Page
Fixes logo and menu hover animations
Updated to use public API for lookup instead of private API
Added version to plugin so we can denote what version is being used in Production versus Staging
=> Minor corrections

assets/javascripts/discourse/templates/connectors/discovery-list-container-top/proper_ad.hbs
Remove Proper from template to fix JS error on community.
Card: https://app.clickup.com/t/c690dx
=> Remove Proper from template
